import React from 'react';
import { glass } from '../styles/theme';

export default function InsightsDrawer({ open, onClose, emotionState, lastBehavior, memory, behaviorContext, stats }) {
  if (!open) return null;
  return <div onClick={onClose} style={styles.back}><aside onClick={(e)=>e.stopPropagation()} style={styles.drawer}><div style={styles.head}><div><h2 style={styles.h2}>Session Insights</h2><p style={styles.p}>Emotion, memory, speech and usage.</p></div><button onClick={onClose} style={styles.close}>×</button></div><Card title="Emotion"><Row label="User mood" value={emotionState?.user_emotion || 'neutral'} /><Row label="AI mode" value={emotionState?.ai_mode || 'balanced'} /><p style={styles.note}>{emotionState?.emotion_reason}</p></Card><Card title="Speech Analysis">{lastBehavior ? <div style={styles.grid}><Metric label="Duration" value={`${lastBehavior.duration_seconds}s`} /><Metric label="Words" value={lastBehavior.word_count} /><Metric label="Hesitations" value={lastBehavior.hesitation_count} /><Metric label="Speed" value={`${lastBehavior.words_per_second}/s`} /><Metric label="Style" value={lastBehavior.speaking_style} /><Metric label="Pause" value={lastBehavior.pause_level} /></div> : <p style={styles.note}>No speech analysis yet.</p>}</Card><Card title="Memory"><Row label="Name" value={memory?.name || 'Not detected'} /><List label="Likes" items={memory?.likes} /><List label="Goals" items={memory?.goals} /><List label="Notes" items={memory?.personal_notes} /></Card><Card title="AI Interpretation"><p style={styles.note}>{behaviorContext}</p></Card><Card title="Stats"><div style={styles.grid}><Metric label="Total" value={stats?.total_user_messages || 0} /><Metric label="Voice" value={stats?.voice_messages || 0} /><Metric label="Text" value={stats?.text_messages || 0} /><Metric label="Interruptions" value={stats?.interruptions || 0} /></div></Card></aside></div>;
}
function Card({title,children}){return <div style={{...glass,borderRadius:22,padding:15,marginBottom:12}}><div style={styles.cardTitle}>{title}</div>{children}</div>;}
function Row({label,value}){return <div style={{marginBottom:10}}><div style={styles.label}>{label}</div><div style={styles.value}>{value}</div></div>;}
function Metric({label,value}){return <div style={styles.metric}><div style={styles.label}>{label}</div><div style={styles.value}>{value}</div></div>;}
function List({label,items}){return <div style={{marginTop:10}}><div style={styles.label}>{label}</div>{items&&items.length>0?<div style={{display:'grid',gap:6,marginTop:6}}>{items.map((item,i)=><div key={i} style={styles.listItem}>{item}</div>)}</div>:<div style={{color:'#64748b',fontSize:13}}>No data yet</div>}</div>;}
const styles={back:{position:'fixed',inset:0,zIndex:50,background:'rgba(2,6,23,.65)',backdropFilter:'blur(8px)',display:'flex',justifyContent:'flex-end'},drawer:{width:410,maxWidth:'92vw',height:'100%',overflowY:'auto',padding:18,background:'rgba(2,6,23,.96)',borderLeft:'1px solid rgba(148,163,184,.18)',boxShadow:'-24px 0 80px rgba(0,0,0,.5)'},head:{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:16},h2:{fontSize:26,fontWeight:950,color:'#fff',letterSpacing:'-.05em',margin:0},p:{marginTop:4,fontSize:13,color:'#94a3b8'},close:{width:38,height:38,borderRadius:'50%',border:'1px solid rgba(255,255,255,.12)',background:'rgba(255,255,255,.06)',color:'#fff',fontSize:24,cursor:'pointer'},cardTitle:{fontSize:15,fontWeight:900,color:'#fff',marginBottom:12},label:{fontSize:12,color:'#94a3b8',marginBottom:4},value:{fontSize:14,color:'#f8fafc',fontWeight:800,textTransform:'capitalize'},note:{fontSize:13,lineHeight:1.6,color:'#cbd5e1',margin:0},grid:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8},metric:{background:'rgba(255,255,255,.05)',border:'1px solid rgba(255,255,255,.08)',borderRadius:14,padding:10},listItem:{background:'rgba(255,255,255,.05)',border:'1px solid rgba(255,255,255,.08)',borderRadius:12,padding:'8px 10px',color:'#e2e8f0',fontSize:13}};
